# gradle/libs.versions.toml

[versions]
# Android SDK versions
compileSdk = "35"
minSdk = "24"
targetSdk = "35"

# App versions
versionCode = "1"
versionName = "1.0"

# Compose
composeBom = "2024.04.01"

# Activity & Navigation
activityCompose = "1.8.2"
navigationCompose = "2.7.7"

# Security
securityCrypto = "1.1.0-alpha06"

# Image Loading
coilCompose = "2.6.0"

# Networking
retrofit = "2.10.0"
okhttp = "4.12.0"
kotlinxSerialization = "1.6.0"
gson = "2.10.1"

# Biometric
biometric = "1.1.0"

# AndroidX Core & AppCompat
coreKtx = "1.13.0"
appCompat = "1.6.1"
material = "1.11.0"
constraintLayout = "2.1.4"

# Desugaring
desugarJdkLibs = "2.0.4"

# Testing
junit = "4.13.2"
androidxJunit = "1.1.5"
espressoCore = "3.5.1"


[libraries]
# Compose
composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
composeUi = { module = "androidx.compose.ui:ui" }
composeUiGraphics = { module = "androidx.compose.ui:ui-graphics" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
composeMaterial3 = { module = "androidx.compose.material3:material3" }

# AndroidX
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
securityCrypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }

# Coil
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }

# Networking
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofitSerializationConverter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Desugaring
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }


[plugins]
# Android Application Plugin
comAndroidApplication = { id = "com.android.application" }

# Kotlin Plugins
orgJetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android" }
orgJetbrainsKotlinPluginCompose = { id = "org.jetbrains.kotlin.plugin.compose" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization" }